- name: Sudo | OS Variables
  include_vars: "{{ lookup('first_found', params) }}"
  vars:
    params:
      files:
        - '{{ansible_distribution}}.yml'
        - '{{ansible_os_family}}.yml'
        - '{{ansible_system}}.yml'
        - default.yaml
      paths:
        - 'vars'
  when: lookup_default_vars is true

- name: 'sudoers.d directory'
  ansible.builtin.file:
    path: "{{ sudoers_dir }}"
    state: directory
    mode: 0755
    owner: 0
    group: 0

- name: Make sure group wheel is not in the sudoers configuration
  ansible.builtin.lineinfile:
    path: "{{ sudoers_file }}"
    state: present
    line: "#includedir {{ sudoers_dir }}"

- name: 'sudoers files'
  ansible.builtin.template:
    src: sudoers.j2
    dest: "{{ sudoers_dir }}/{{ item.key }}"
    validate: 'visudo -cf %s'
    mode: 0440
  loop: "{{ sudoers_files | dict2items }}"